#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_BINS 100
#define MAX_VEHICLES 50
#define MAX_DRIVERS 50
#define MAX_COMPLAINTS 200
#define MAX_ROUTE_STOPS 100

#define MAX_NAME_LENGTH 50
#define MAX_ADDRESS_LENGTH 120
#define MAX_DESCRIPTION_LENGTH 200

#define MAX_FILL_LEVEL 100.0f

#define CRITICAL_PRIORITY_THRESHOLD 85.0f
#define HIGH_PRIORITY_THRESHOLD 70.0f
#define MEDIUM_PRIORITY_THRESHOLD 50.0f

#define LOW_FUEL_THRESHOLD 20.0f
#define FULL_FUEL_LEVEL 100.0f

#define DEFAULT_FUEL_EFFICIENCY 8.0f

#define DEPOT_X 5.0f
#define DEPOT_Y 5.0f

#define BIN_CAPACITY_KG 500.0f

#endif